workspace = { members = [ "actix_base_error_handling", "tutor-web-service","tutor-nodb", "tutor-web-app-ssr"] }
[package]
name = "eztutors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
